// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy40cKvg7mPAAMvKaPxXXHnjYKKECOKWQ',
    appId: '1:1049902142714:web:2f5f61665b417e7a1c6543',
    messagingSenderId: '1049902142714',
    projectId: 'chatting-b861b',
    authDomain: 'chatting-b861b.firebaseapp.com',
    storageBucket: 'chatting-b861b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbD1hTJqIMuocbu39-35deiJRHfyJZpVk',
    appId: '1:1049902142714:android:f4d1c488b2c422f51c6543',
    messagingSenderId: '1049902142714',
    projectId: 'chatting-b861b',
    storageBucket: 'chatting-b861b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03IHUT4tyJWYZYRCZkR5yXSyQhsTMbmo',
    appId: '1:104830974207:ios:14686d6ad00e84ee1c34ca',
    messagingSenderId: '104830974207',
    projectId: 'chatapp-e54f7',
    storageBucket: 'chatapp-e54f7.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC03IHUT4tyJWYZYRCZkR5yXSyQhsTMbmo',
    appId: '1:104830974207:ios:14686d6ad00e84ee1c34ca',
    messagingSenderId: '104830974207',
    projectId: 'chatapp-e54f7',
    storageBucket: 'chatapp-e54f7.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt3_wKYMX72i2HY5kbL4Xm3VwtczvUgqs',
    appId: '1:104830974207:web:c08cf63742b2f22b1c34ca',
    messagingSenderId: '104830974207',
    projectId: 'chatapp-e54f7',
    authDomain: 'chatapp-e54f7.firebaseapp.com',
    storageBucket: 'chatapp-e54f7.appspot.com',
    measurementId: 'G-0FJ1EN2GRD',
  );
}